spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8015/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:8016/
          predicates:
            - Path= /products/**